### ISSUE TITLE
Inquiry of an error

### ISSUE THREAD

**Issue by samwelnyandoro** [GavinNyamboga/shopperApp#1]
![Screenshot (180)](https://user-images.githubusercontent.com/36915374/133579059-83caa357-adef-4c80-8d33-2c4ab6c9cbbe.png)
am experiencing the above error on my accesstokeninterceptor.java file kindly help

**Comment by GavinNyamboga** [comment]
Hope you created an account on [safaricom developer portal](https://developer.safaricom.co.ke/home) and registered your app. From there you will be given the Consumer Key and Consumer Secret. You can follow this tutorial on setting up Mpesa in Android [M-PESA Integration on Android](https://medium.com/devcnairobi/m-pesa-integration-on-android-part-1-a0983cd3275d)

**Comment by samwelnyandoro** [comment]
Have tried following step by step but am experiencing the error i sent you
yesterday kindly help me.Thank you

**Comment by GavinNyamboga** [comment]
![image](https://user-images.githubusercontent.com/27638189/133738821-efdb651f-37fb-43e6-89c6-6d4cc8d2eef4.png)
did you add this to your `build.gradle` and `gradle.properties` files?

**Comment by samwelnyandoro** [comment]
Yes, I did.

**Comment by GavinNyamboga** [comment]
so what is the error you are getting specifically?

**Comment by samwelnyandoro** [comment]
See the screenshot below is that an error when it indicates like that in
build.gradle app module??
